# Generated by Django 4.1.3 on 2022-11-08 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_question', models.CharField(blank=True, max_length=150, null=True)),
                ('intitule_question', models.CharField(blank=True, max_length=150, null=True)),
                ('coeff_bonne_reponse', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReponsesPropose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonne_reponse', models.BooleanField(default=False)),
                ('intitule_reponse', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SecteursActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_secteur', models.CharField(db_column='Type_secteur', max_length=50)),
                ('titre_secteur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_deploiment', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteminimal', models.IntegerField(blank=True, db_column='NoteMinimal', null=True)),
                ('etat_brouillon', models.IntegerField(blank=True, db_column='Etat_brouillon', null=True)),
                ('nom_quizz', models.CharField(blank=True, max_length=70, null=True)),
                ('id_sa', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.secteursactivite')),
                ('idsession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('role', models.CharField(default='salarié', max_length=50, verbose_name='role')),
                ('naissance', models.DateField(blank=True, null=True)),
                ('code_postal', models.CharField(default='974', max_length=30)),
                ('ville', models.CharField(blank=True, max_length=60, null=True)),
                ('matricul', models.CharField(max_length=50, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('secteur_activiter', models.ForeignKey(db_column='ID_SA', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.secteursactivite')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReponseALaQuestion',
            fields=[
                ('idreponse', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.reponsespropose')),
                ('idquestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.questions')),
            ],
            options={
                'unique_together': {('idreponse', 'idquestion')},
            },
        ),
        migrations.CreateModel(
            name='Possede',
            fields=[
                ('idquizz', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.quizz')),
                ('idquestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.questions')),
            ],
            options={
                'unique_together': {('idquizz', 'idquestion')},
            },
        ),
        migrations.CreateModel(
            name='Participe',
            fields=[
                ('matricule_salarie', models.OneToOneField(db_column='Matricule_Salarie', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idsession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sessions')),
            ],
            options={
                'unique_together': {('matricule_salarie', 'idsession')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueReponsesSelectionner',
            fields=[
                ('matricule_salarie', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_repondu', models.DateTimeField(blank=True, null=True)),
                ('entrainement', models.BooleanField(blank=True, null=True)),
                ('idquestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.questions')),
                ('idquizz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.quizz')),
                ('idreponse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.reponsespropose')),
            ],
            options={
                'unique_together': {('matricule_salarie', 'idquizz', 'idreponse', 'idquestion')},
            },
        ),
    ]
